### ISSUE TITLE
using the notebook generate_plots.ipynb.

### ISSUE THREAD

**Issue by SerendipityLY** [sayantanauddy/clfd#1]
how to generate plots using the notebook generate_plots.ipynb?

thanks for your answer

**Comment by sayantanauddy** [comment]
Sorry for the late reply. For using `generate_plots.ipynb` you would need to first run all the experiments by using the commands given in the files `commands_*.txt`. After this, each cell of the notebook could be run in sequence to generate the plots. Now, however, the code has been updated and the plotting setup has changed. The old plotting notebook (`generate_plots.ipynb`) is now obsolete. In the README, I included new descriptions for the generated log files.
